/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;

import assignment.Payment;
import assignment.RoomInfo;
import assignment.StudentApplication;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author billytiong
 */
public class PaymentPage extends javax.swing.JFrame {
    String currentStudentName;
    int selectedDuration;
    String selectedRoomType;
    String selectedRoomNumber;
    int totalFee;

    /**
     * Creates new form Payment
     */
    public PaymentPage() {
        initComponents();
        this.currentStudentName = "Billy";
        this.selectedDuration = 12;
        this.selectedRoomType = "Single Room";
        this.selectedRoomNumber = "A101";
        populateData();
    }
    
    public PaymentPage(String username, int duration, String roomType, String roomNumber) {
        this();
        this.currentStudentName = username;
        this.selectedDuration = duration;
        this.selectedRoomType = roomType;
        this.selectedRoomNumber = roomNumber;
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        pay_label_duration = new javax.swing.JLabel();
        pay_text_duration = new javax.swing.JTextField();
        pay_label_title = new javax.swing.JLabel();
        pay_label_roomtype = new javax.swing.JLabel();
        pay_text_fee = new javax.swing.JTextField();
        pay_label_fee = new javax.swing.JLabel();
        pay_text_roomtype = new javax.swing.JTextField();
        pay_button_pay = new javax.swing.JButton();
        pay_button_backra = new javax.swing.JButton();
        pay_label_month = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pay_label_duration.setText("Duration            :");

        pay_text_duration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pay_text_duration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pay_text_durationMouseClicked(evt);
            }
        });
        pay_text_duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_text_durationActionPerformed(evt);
            }
        });

        pay_label_title.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        pay_label_title.setText("Payment");

        pay_label_roomtype.setText("Room Type       :");

        pay_label_fee.setText("Fee                   :");

        pay_text_roomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_text_roomtypeActionPerformed(evt);
            }
        });

        pay_button_pay.setText("Punch Me");
        pay_button_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_button_payActionPerformed(evt);
            }
        });

        pay_button_backra.setText("Let Me Think");
        pay_button_backra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_button_backraActionPerformed(evt);
            }
        });

        pay_label_month.setText("Month");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pay_label_duration)
                            .addComponent(pay_label_fee)
                            .addComponent(pay_label_roomtype))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pay_text_roomtype, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(pay_text_fee)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pay_text_duration)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pay_label_month))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(pay_label_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(pay_button_pay)
                        .addGap(18, 18, 18)
                        .addComponent(pay_button_backra)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pay_label_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay_label_roomtype)
                    .addComponent(pay_text_roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay_label_fee)
                    .addComponent(pay_text_fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay_label_duration)
                    .addComponent(pay_text_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_label_month))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pay_button_pay)
                    .addComponent(pay_button_backra))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pay_text_durationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay_text_durationMouseClicked
        pay_text_duration.setText(" ");
    }//GEN-LAST:event_pay_text_durationMouseClicked

    private void pay_text_durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_text_durationActionPerformed
        
    }//GEN-LAST:event_pay_text_durationActionPerformed

    private void pay_button_backraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_button_backraActionPerformed
        RoomApplicationPage ra = new RoomApplicationPage(currentStudentName);
        ra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pay_button_backraActionPerformed

    private void pay_button_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_button_payActionPerformed
        // add payment to txt file
        LocalDate currentDate = LocalDate.now();
        String currentDateString = currentDate.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));

        Payment newPayment = new Payment();
        newPayment.setStudentName(currentStudentName);
        newPayment.setTotal(totalFee);
        newPayment.setDate(currentDateString);

        Payment.addPaymentToFile(newPayment);
        
        // add application to txt file
        StudentApplication newStudentApplication = new StudentApplication();
        newStudentApplication.setStatus("Ongoing");
        newStudentApplication.setStudentName(currentStudentName);
        newStudentApplication.setRoomNumber(selectedRoomNumber);
        newStudentApplication.setBookingDate(currentDateString);
        newStudentApplication.setDuration(Integer.toString(selectedDuration));
        newStudentApplication.setreason("-");
        

        // add new application to file
        StudentApplication.addStudentApplicationtToFile(newStudentApplication);
        
        // Show a message box with "Payment success" message
        JOptionPane.showMessageDialog(this, "Payment Success", "Payment", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_pay_button_payActionPerformed

    private void pay_text_roomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_text_roomtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pay_text_roomtypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton pay_button_backra;
    private javax.swing.JButton pay_button_pay;
    private javax.swing.JLabel pay_label_duration;
    private javax.swing.JLabel pay_label_fee;
    private javax.swing.JLabel pay_label_month;
    private javax.swing.JLabel pay_label_roomtype;
    private javax.swing.JLabel pay_label_title;
    private javax.swing.JTextField pay_text_duration;
    private javax.swing.JTextField pay_text_fee;
    private javax.swing.JTextField pay_text_roomtype;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        pay_text_roomtype.setText(selectedRoomType);
        pay_text_duration.setText(String.valueOf(selectedDuration));

        int monthlyFee = RoomInfo.getFeeByRoomType(selectedRoomType);

        this.totalFee = monthlyFee * selectedDuration;

        pay_text_fee.setText(String.valueOf(this.totalFee));

    }
}
