/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;

import assignment.Student;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author billytiong
 */
public class ProfilePage extends javax.swing.JFrame {

    String currentStudentName;
    Student student;

    /**
     * Creates new form Profile
     */
    public ProfilePage() {
        currentStudentName = "Billy";
        initComponents();
        this.student = Student.getStudentByUsername(currentStudentName);
        populateStudentInfo();
    }

    public ProfilePage(String username) {
        this.currentStudentName = username;
        this.student = Student.getStudentByUsername(username);
        initComponents();
        populateStudentInfo();
    }

    private void populateStudentInfo() {
        System.out.println("Hi function " + this.currentStudentName);
        pf_text_name.setText(String.valueOf(this.currentStudentName));
        pf_text_email.setText(String.valueOf(student.getStudentEmail()));
        pf_text_contact.setText(String.valueOf(student.getStudentContact()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pf_label_title = new javax.swing.JLabel();
        pf_label_name = new javax.swing.JLabel();
        pf_label_email = new javax.swing.JLabel();
        pf_label_contact = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pf_button_updatename = new javax.swing.JButton();
        pf_button_updateemail = new javax.swing.JButton();
        pf_button_updatecontact = new javax.swing.JButton();
        pf_text_name = new javax.swing.JTextField();
        pf_text_email = new javax.swing.JTextField();
        pf_text_contact = new javax.swing.JTextField();
        pf_button_backvi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pf_label_title.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        pf_label_title.setText("Profile");

        pf_label_name.setText("Name    :");

        pf_label_email.setText("E-mail   :");

        pf_label_contact.setText("Contact :");

        pf_button_updatename.setText("Update");
        pf_button_updatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_button_updatenameActionPerformed(evt);
            }
        });

        pf_button_updateemail.setText("Update");
        pf_button_updateemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_button_updateemailActionPerformed(evt);
            }
        });

        pf_button_updatecontact.setText("Update");
        pf_button_updatecontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_button_updatecontactActionPerformed(evt);
            }
        });

        pf_text_name.setEditable(false);
        pf_text_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_text_nameActionPerformed(evt);
            }
        });

        pf_text_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_text_emailActionPerformed(evt);
            }
        });

        pf_button_backvi.setText("Back");
        pf_button_backvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_button_backviActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(pf_button_backvi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pf_label_title)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pf_label_email)
                            .addComponent(pf_label_name)
                            .addComponent(pf_label_contact))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pf_text_name, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pf_button_updateemail)
                                    .addComponent(pf_button_updatecontact)
                                    .addComponent(pf_button_updatename)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pf_text_contact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pf_text_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)))
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(pf_label_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_label_name)
                    .addComponent(pf_button_updatename, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_label_email)
                    .addComponent(pf_button_updateemail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_text_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pf_label_contact)
                    .addComponent(pf_button_updatecontact, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_text_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(pf_button_backvi)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pf_button_backviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_button_backviActionPerformed
        ViewInfoPage vi = new ViewInfoPage(currentStudentName);
        vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pf_button_backviActionPerformed

    private void pf_button_updatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_button_updatenameActionPerformed
        String updatedName = pf_text_name.getText(); // Get the updated name from the text field
    
        // Update the field with the updated value
        pf_text_name.setText(updatedName);

        // Write the new field to the file
        // updateFieldInFile(updatedName, "studentFile", "Name");
    }//GEN-LAST:event_pf_button_updatenameActionPerformed

    private void pf_button_updateemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_button_updateemailActionPerformed
        String updatedEmail = pf_text_email.getText(); // Get the updated name from the text field
    
        // Update the field with the updated value
        pf_text_email.setText(updatedEmail);

        // Write the new field to the file
        this.student.updateFieldInFile(updatedEmail, "email");

    }//GEN-LAST:event_pf_button_updateemailActionPerformed

    private void pf_text_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_text_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_text_nameActionPerformed

    private void pf_button_updatecontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_button_updatecontactActionPerformed
        String updatedContact = pf_text_contact.getText(); // Get the updated name from the text field
    
        // Update the field with the updated value
        pf_text_contact.setText(updatedContact);

        // Write the new field to the file
        this.student.updateFieldInFile(updatedContact, "contact");
    }//GEN-LAST:event_pf_button_updatecontactActionPerformed

    private void pf_text_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_text_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_text_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilePage().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton pf_button_backvi;
    private javax.swing.JButton pf_button_updatecontact;
    private javax.swing.JButton pf_button_updateemail;
    private javax.swing.JButton pf_button_updatename;
    private javax.swing.JLabel pf_label_contact;
    private javax.swing.JLabel pf_label_email;
    private javax.swing.JLabel pf_label_name;
    private javax.swing.JLabel pf_label_title;
    private javax.swing.JTextField pf_text_contact;
    private javax.swing.JTextField pf_text_email;
    private javax.swing.JTextField pf_text_name;
    // End of variables declaration//GEN-END:variables
}
