/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;

import assignment.Student;
import assignment.User;

/**
 *
 * @author billytiong
 */
public class RegisterPage extends javax.swing.JFrame {
    String username;
    String password;
    int contact;
    String email;
    

    /**
     * Creates new form FirstPage
     */
    public RegisterPage() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ng_button_cancel = new javax.swing.JButton();
        ng_button_register = new javax.swing.JButton();
        ng_label_name = new javax.swing.JLabel();
        ng_label_contact = new javax.swing.JLabel();
        ng_label_title = new javax.swing.JLabel();
        ng_label_email = new javax.swing.JLabel();
        ng_label_password = new javax.swing.JLabel();
        ng_text_contact = new javax.swing.JTextField();
        ng_text_name = new javax.swing.JTextField();
        ng_text_email = new javax.swing.JTextField();
        ng_text_password = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ng_button_cancel.setText("Cancel");
        ng_button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ng_button_cancelActionPerformed(evt);
            }
        });

        ng_button_register.setText("Register");
        ng_button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ng_button_registerActionPerformed(evt);
            }
        });

        ng_label_name.setText("Name       :");

        ng_label_contact.setText("Contact    :");

        ng_label_title.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        ng_label_title.setText("New Register");

        ng_label_email.setText("E-mail      :");

        ng_label_password.setText("Password :");

        ng_text_contact.setToolTipText("");

        ng_text_name.setToolTipText("");

        ng_text_email.setToolTipText("");

        ng_text_password.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ng_label_contact)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ng_text_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(ng_button_register)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ng_button_cancel))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ng_label_name)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ng_label_password)
                                            .addComponent(ng_label_email)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ng_text_name, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ng_text_email, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ng_text_password, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(ng_label_title)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ng_label_title)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ng_label_name)
                    .addComponent(ng_text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ng_label_contact)
                    .addComponent(ng_text_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ng_label_email)
                    .addComponent(ng_text_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ng_label_password)
                    .addComponent(ng_text_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ng_button_cancel)
                    .addComponent(ng_button_register))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ng_button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ng_button_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ng_button_cancelActionPerformed

    private void ng_button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ng_button_registerActionPerformed

        User newUser = new User();
        username = ng_text_name.getText();
        password = ng_text_password.getText();
        newUser.setUsername(username);
        newUser.setPassword(password);
        newUser.setRole("Student");
            
        User.addUserToFile(newUser);
        
        Student newStudent = new Student();
        //contact = ng_text_contact.getText();
        email = ng_text_email.getText();
        
        newStudent.setUsername(username);
        newStudent.setStudentContact(Integer.toString(contact));
        newStudent.setStudentEmail(email);
        
        Student.addStudentToFile(newStudent);
    }//GEN-LAST:event_ng_button_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ng_button_cancel;
    private javax.swing.JButton ng_button_register;
    private javax.swing.JLabel ng_label_contact;
    private javax.swing.JLabel ng_label_email;
    private javax.swing.JLabel ng_label_name;
    private javax.swing.JLabel ng_label_password;
    private javax.swing.JLabel ng_label_title;
    private javax.swing.JTextField ng_text_contact;
    private javax.swing.JTextField ng_text_email;
    private javax.swing.JTextField ng_text_name;
    private javax.swing.JTextField ng_text_password;
    // End of variables declaration//GEN-END:variables
}
