/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;

/**
 *
 * @author billytiong
 */
public class RoomApplicationPage extends javax.swing.JFrame {
    
    String currentStudentName;
    /**
     * Creates new form RoomApplication
     */
    public RoomApplicationPage() {
        initComponents();
    }
    
    public RoomApplicationPage(String username){
        this();
        this.currentStudentName = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ra_combobox_roomtype = new javax.swing.JComboBox<>();
        ra_label_roomtype = new javax.swing.JLabel();
        ra_text_duration = new javax.swing.JTextField();
        ra_label_duration = new javax.swing.JLabel();
        ra_label_availableroom = new javax.swing.JLabel();
        ra_combobox_availableroom = new javax.swing.JComboBox<>();
        ra_label_title = new javax.swing.JLabel();
        ra_button_gopay = new javax.swing.JButton();
        ra_button_backsmp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ra_combobox_roomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Room", "Double Room", "Triple Room", "Quad Room" }));

        ra_label_roomtype.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ra_label_roomtype.setText("Room Type");

        ra_label_duration.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ra_label_duration.setText("Duration");

        ra_label_availableroom.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ra_label_availableroom.setText("Available Room");

        ra_combobox_availableroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ra_label_title.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        ra_label_title.setText("Find Room that is Good & Suitable to U !!!");

        ra_button_gopay.setText("Punch me");
        ra_button_gopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra_button_gopayActionPerformed(evt);
            }
        });

        ra_button_backsmp.setText("Back");
        ra_button_backsmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra_button_backsmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ra_label_title)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ra_label_roomtype)
                            .addComponent(ra_combobox_roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ra_text_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ra_label_duration)
                                .addGap(16, 16, 16)))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ra_label_availableroom)
                            .addComponent(ra_combobox_availableroom, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(ra_button_gopay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ra_button_backsmp)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ra_label_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ra_label_roomtype)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ra_label_duration)
                        .addComponent(ra_label_availableroom)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ra_combobox_roomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ra_text_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ra_combobox_availableroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ra_button_gopay)
                    .addComponent(ra_button_backsmp))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ra_button_gopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra_button_gopayActionPerformed
        PaymentPage pay = new PaymentPage(currentStudentName);
        pay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ra_button_gopayActionPerformed

    private void ra_button_backsmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra_button_backsmpActionPerformed
        StudentMainPage smp = new StudentMainPage(currentStudentName);
        smp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ra_button_backsmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomApplicationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomApplicationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomApplicationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomApplicationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomApplicationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ra_button_backsmp;
    private javax.swing.JButton ra_button_gopay;
    private javax.swing.JComboBox<String> ra_combobox_availableroom;
    private javax.swing.JComboBox<String> ra_combobox_roomtype;
    private javax.swing.JLabel ra_label_availableroom;
    private javax.swing.JLabel ra_label_duration;
    private javax.swing.JLabel ra_label_roomtype;
    private javax.swing.JLabel ra_label_title;
    private javax.swing.JTextField ra_text_duration;
    // End of variables declaration//GEN-END:variables
}
