/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;

/**
 *
 * @author billytiong
 */
public class ViewInfoPage extends javax.swing.JFrame {
    
    String currentStudentName;
    /**
     * Creates new form Application
     */
    public ViewInfoPage() {
        currentStudentName = "Billy";
        initComponents();
    }
    
    public ViewInfoPage(String username){
        this();
        this.currentStudentName = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vi_label_title = new javax.swing.JLabel();
        vi_button_profile = new javax.swing.JButton();
        vi_button_hr = new javax.swing.JButton();
        vi_label_profile = new javax.swing.JLabel();
        vi_label_hr = new javax.swing.JLabel();
        vi_button_backsmp = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vi_label_title.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        vi_label_title.setText("View Info");

        vi_button_profile.setText("Punch Me");
        vi_button_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vi_button_profileActionPerformed(evt);
            }
        });

        vi_button_hr.setText("Punch Me");
        vi_button_hr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vi_button_hrActionPerformed(evt);
            }
        });

        vi_label_profile.setText("Personal Info Portal       :");

        vi_label_hr.setText("Historical Record Portal :");

        vi_button_backsmp.setText("Back");
        vi_button_backsmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vi_button_backsmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(vi_label_hr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vi_button_hr)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(vi_label_title)
                        .addGap(138, 138, 138))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vi_label_profile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vi_button_profile)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(vi_button_backsmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(vi_label_title)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vi_label_profile)
                    .addComponent(vi_button_profile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vi_label_hr)
                    .addComponent(vi_button_hr))
                .addGap(18, 18, 18)
                .addComponent(vi_button_backsmp)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vi_button_hrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vi_button_hrActionPerformed
        HistoricalReportPage hr = new HistoricalReportPage(currentStudentName);
        hr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vi_button_hrActionPerformed

    private void vi_button_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vi_button_profileActionPerformed
        ProfilePage pf = new ProfilePage(currentStudentName);
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vi_button_profileActionPerformed

    private void vi_button_backsmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vi_button_backsmpActionPerformed
        StudentMainPage smp = new StudentMainPage(currentStudentName);
        smp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vi_button_backsmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInfoPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton vi_button_backsmp;
    private javax.swing.JButton vi_button_hr;
    private javax.swing.JButton vi_button_profile;
    private javax.swing.JLabel vi_label_hr;
    private javax.swing.JLabel vi_label_profile;
    private javax.swing.JLabel vi_label_title;
    // End of variables declaration//GEN-END:variables
}
